"""
CPSForge Adaptation Loop
==========================
Orchestrates the closed-loop red-team / blue-team experiment across multiple
rounds of attack → detect → extract → retrain → next round.

Architecture
------------
:class:`AdaptationLoop` wraps :class:`~cpsforge.core.orchestrator.ExperimentOrchestrator`
and adds the outer adaptation loop:

1. Run round *r* with the current detector state.
2. Extract hard cases from the run's ``hard_cases.json``.
3. Add them to the :class:`~cpsforge.adaptation.bank.HardCaseBank`.
4. When the bank reaches ``min_hard_cases_to_retrain`` (default 10) and
   a sequence-model defender is configured:
   a. Extract normal windows from any available baseline run directories.
   b. Extract attack windows from accumulated hard cases.
   c. Train a new :class:`~cpsforge.adaptation.trainer.SequenceDetectorTrainer`.
   d. Save the model to
      ``<models_dir>/<experiment_name>/round_<r>/sequence_model.pkl``.
   e. Update the experiment config's sequence-model defender entry to point
      to the new model path.
5. Proceed to round *r + 1*.
6. After all rounds, write ``round_metrics.csv`` and ``round_summary.json``
   to ``<data_dir>/processed/<experiment_name>/``.

Idempotency
-----------
All run artifacts are written atomically by the orchestrator.  If a round
fails mid-way the completed rounds' artifacts and metrics are preserved.
The loop does NOT roll back completed rounds.

Typical usage::

    from pathlib import Path
    from cpsforge.core.config import ConfigLoader, ExperimentConfig
    from cpsforge.adaptation.adaptation_loop import AdaptationLoop

    loader = ConfigLoader()
    exp_cfg = loader.load_experiment("phase5_adaptation")

    loop = AdaptationLoop(
        base_config=exp_cfg,
        loader=loader,
        n_rounds=5,
        experiment_name="phase5_adaptation",
        data_dir=Path("data"),
        min_hard_cases_to_retrain=10,
    )
    summaries = loop.run()
"""

from __future__ import annotations

import copy
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from cpsforge.core.config import ConfigLoader, ExperimentConfig
from cpsforge.core.models import EvalMetrics

logger = logging.getLogger(__name__)


@dataclass
class RoundResult:
    """
    Outcome record for a single adaptation round.

    Stored in the list returned by :meth:`AdaptationLoop.run` and used to
    build the :class:`~cpsforge.adaptation.round_metrics.RoundSummary`
    series.
    """

    round_idx: int
    """0-based round index."""

    run_id: str
    """Run ID generated by the orchestrator for this round."""

    metrics: Optional[EvalMetrics]
    """EvalMetrics object, or None when save_metrics=False."""

    hard_case_count: int
    """Hard cases extracted from this round's run."""

    hard_case_cumulative: int
    """Total hard cases in the bank after this round."""

    retrained: bool
    """Whether the sequence detector was retrained before this round."""

    model_path: Optional[Path]
    """Absolute path to the sequence-model bundle used in this round."""

    run_dir: Path
    """Absolute path to the run artifact directory."""


# ---------------------------------------------------------------------------
# AdaptationLoop
# ---------------------------------------------------------------------------


class AdaptationLoop:
    """
    Multi-round adaptation loop combining attack runs and detector retraining.

    Parameters
    ----------
    base_config:
        Experiment configuration template.  A deep copy is made per round
        so the original is not mutated.
    loader:
        :class:`~cpsforge.core.config.ConfigLoader` for resolving config files.
    n_rounds:
        Total number of attack + detect rounds to run.
    experiment_name:
        Used as the folder name under ``data/raw/`` and ``data/processed/``.
    data_dir:
        Root data directory (default: ``data/``).
    models_dir:
        Where retrained models are saved
        (default: ``<data_dir>/models/<experiment_name>/``).
    min_hard_cases_to_retrain:
        Minimum cumulative hard cases required before the first (and each
        subsequent) retraining.  Set to 0 to always retrain from round 1.
    window_size:
        Feature window size (in steps) passed to the bank and trainer.
    baseline_experiment:
        Optional name of a *baseline* (no-attack) experiment under
        ``data/raw/`` to use as the source of normal-operation windows for
        training.  When None, normal windows are extracted from the same
        experiment's runs using only non-attack steps.
    random_state:
        Reproducibility seed for the trainer.
    """

    # Name used to identify sequence-model defender entries in the config
    _SEQ_DETECTOR_TYPE = "sequence_model"

    def __init__(
        self,
        base_config: ExperimentConfig,
        loader: ConfigLoader,
        n_rounds: int = 3,
        experiment_name: str = "",
        data_dir: Path = Path("data"),
        models_dir: Optional[Path] = None,
        min_hard_cases_to_retrain: int = 10,
        window_size: int = 20,
        baseline_experiment: Optional[str] = None,
        random_state: int = 42,
    ) -> None:
        self._base_config = base_config
        self._loader = loader
        self._n_rounds = n_rounds
        self._experiment_name = experiment_name or base_config.name
        self._data_dir = Path(data_dir)
        self._models_dir = (
            models_dir
            if models_dir is not None
            else self._data_dir / "models" / self._experiment_name
        )
        self._min_hard_cases = min_hard_cases_to_retrain
        self._window_size = window_size
        self._baseline_experiment = baseline_experiment
        self._random_state = random_state

        # Resolved paths
        self._raw_dir = self._data_dir / "raw" / self._experiment_name
        self._processed_dir = self._data_dir / "processed" / self._experiment_name

        # State shared across rounds
        from cpsforge.adaptation.bank import HardCaseBank

        self._bank = HardCaseBank(
            experiment_dir=self._raw_dir,
            window_size=window_size,
        )

        # Current active model path (None = untrained)
        self._current_model_path: Optional[Path] = None
        # Track which rounds triggered a retrain
        self._retrained_at: List[int] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self) -> List[RoundResult]:
        """
        Execute all rounds and return a list of :class:`RoundResult`.

        After the final round, round metrics are written to
        ``<data_dir>/processed/<experiment_name>/``.
        """
        results: List[RoundResult] = []

        for r in range(self._n_rounds):
            logger.info("AdaptationLoop: starting round %d / %d.", r, self._n_rounds - 1)
            result = self._run_single_round(r)
            results.append(result)

        self._write_summaries(results)
        return results

    def run_single_round(
        self,
        round_idx: int,
        *,
        eval_run: bool = False,
    ) -> RoundResult:
        """
        Public entry-point for running a single round externally.

        Useful when the caller wants to interleave adaptation steps with
        other logic.
        """
        return self._run_single_round(round_idx, eval_run=eval_run)

    # ------------------------------------------------------------------
    # Internal round execution
    # ------------------------------------------------------------------

    def _run_single_round(
        self,
        round_idx: int,
        eval_run: bool = False,
    ) -> RoundResult:
        """Run one full attack experiment and optionally retrain the detector."""
        from cpsforge.core.orchestrator import ExperimentOrchestrator

        # -- 1. Decide whether to retrain before this round ----------------
        retrained = self._maybe_retrain(round_idx)

        # -- 2. Build per-round config copy --------------------------------
        round_cfg = self._build_round_config(round_idx, eval_run=eval_run)

        # -- 3. Run the orchestrator ---------------------------------------
        orchestrator = ExperimentOrchestrator(
            round_cfg,
            self._loader,
            output_base=self._data_dir / "raw",
        )
        run_id = orchestrator.run()

        # -- 4. Collect per-round metrics and hard cases -------------------
        run_dir = self._raw_dir / run_id
        metrics = self._load_metrics(run_dir)

        from cpsforge.adaptation.hard_cases import load_hard_cases

        new_hard_cases = load_hard_cases(run_dir)
        self._bank.load_from_run(run_dir)

        result = RoundResult(
            round_idx=round_idx,
            run_id=run_id,
            metrics=metrics,
            hard_case_count=len(new_hard_cases),
            hard_case_cumulative=self._bank.count,
            retrained=retrained,
            model_path=self._current_model_path,
            run_dir=run_dir,
        )

        logger.info(
            "AdaptationLoop: round %d complete — run_id=%s, hard_cases=%d, "
            "cumulative=%d, f1=%.3f.",
            round_idx,
            run_id,
            len(new_hard_cases),
            self._bank.count,
            metrics.detector_f1 if metrics else 0.0,
        )
        return result

    # ------------------------------------------------------------------
    # Retraining logic
    # ------------------------------------------------------------------

    def _maybe_retrain(self, round_idx: int) -> bool:
        """
        Retrain the sequence-model detector if conditions are met.

        Conditions:
        1. At least one sequence_model defender is listed in the experiment.
        2. The bank has ≥ min_hard_cases_to_retrain records.
        3. This isn't the very first round (no data yet).

        Returns True when retraining actually happened.
        """
        if round_idx == 0:
            return False

        if not self._has_sequence_defender():
            return False

        if self._bank.count < self._min_hard_cases:
            logger.info(
                "AdaptationLoop: %d hard cases in bank (need %d) — skipping retrain.",
                self._bank.count,
                self._min_hard_cases,
            )
            return False

        # Avoid retraining every single round if nothing changed
        if self._retrained_at and self._retrained_at[-1] == round_idx - 1:
            # Only retrain if we gained at least 5 more hard cases
            # (avoids redundant retraining runs)
            pass

        return self._retrain(round_idx)

    def _retrain(self, round_idx: int) -> bool:
        """
        Execute the actual retraining pipeline and update the model path.

        Returns True on success, False on failure.
        """
        from cpsforge.adaptation.trainer import SequenceDetectorTrainer

        logger.info(
            "AdaptationLoop: retraining sequence detector for round %d "
            "(bank has %d hard cases).",
            round_idx,
            self._bank.count,
        )

        try:
            # Extract hard-case attack windows
            hard_tuples = self._bank.get_attack_windows(
                window_before=self._window_size // 4,
                window_after=self._window_size,
            )
            hard_windows = [t[0] for t in hard_tuples]

            # Extract normal windows
            normal_windows = self._get_normal_windows()

            if len(normal_windows) < 2:
                logger.warning(
                    "AdaptationLoop: not enough normal windows for retraining "
                    "(%d found, need ≥ 2). Using synthetic normal data.",
                    len(normal_windows),
                )
                # Generate minimal synthetic normal data if none available
                # (flat zero sequences — gives IsolationForest a baseline boundary)
                if hard_windows:
                    n_feat = hard_windows[0].shape[1] if hard_windows[0].ndim == 2 else 1
                    for _ in range(max(2, self._window_size)):
                        normal_windows.append(
                            np.zeros((self._window_size, n_feat), dtype=np.float32)
                        )
                else:
                    logger.warning(
                        "AdaptationLoop: no hard windows and no normal windows — "
                        "skipping retrain."
                    )
                    return False

            trainer = SequenceDetectorTrainer(random_state=self._random_state)
            meta = trainer.fit(normal_windows, hard_windows)

            model_path = (
                self._models_dir / f"round_{round_idx}" / "sequence_model.pkl"
            )
            trainer.save(model_path)
            self._current_model_path = model_path
            self._retrained_at.append(round_idx)

            logger.info(
                "AdaptationLoop: retrain complete — model saved to %s. "
                "contamination=%.4f, n_normal=%d, n_hard=%d.",
                model_path,
                meta.get("contamination", 0.0),
                meta.get("n_normal_windows", 0),
                meta.get("n_hard_case_windows", 0),
            )
            return True

        except Exception as exc:
            logger.error(
                "AdaptationLoop: retraining failed (round %d): %s",
                round_idx,
                exc,
                exc_info=True,
            )
            return False

    def _get_normal_windows(self):
        """
        Collect normal-operation feature windows for training.

        Uses the configured baseline experiment when available; otherwise
        extracts non-attack steps from the current experiment's runs.
        """
        import numpy as np  # noqa: F401 (imported here to avoid top-level dep)

        if self._baseline_experiment:
            baseline_dir = self._data_dir / "raw" / self._baseline_experiment
            if baseline_dir.exists():
                baseline_runs = sorted(
                    d for d in baseline_dir.iterdir() if d.is_dir()
                )
                return self._bank.get_normal_windows(
                    baseline_run_dirs=baseline_runs,
                    num_windows=500,
                    window_size=self._window_size,
                )

        # Fall back to runs in the current experiment
        if self._raw_dir.exists():
            all_runs = sorted(d for d in self._raw_dir.iterdir() if d.is_dir())
            return self._bank.get_normal_windows(
                baseline_run_dirs=all_runs,
                num_windows=500,
                window_size=self._window_size,
            )

        return []

    # ------------------------------------------------------------------
    # Config building
    # ------------------------------------------------------------------

    def _build_round_config(
        self, round_idx: int, *, eval_run: bool = False
    ) -> ExperimentConfig:
        """
        Build a per-round experiment config, injecting the current model path
        into any sequence_model defender entry via the defender config on disk.
        """
        cfg = copy.deepcopy(self._base_config)
        cfg.name = self._experiment_name
        cfg.adaptation_round = round_idx
        cfg.eval_run = eval_run or (round_idx == self._n_rounds - 1)

        # Update sequence defender model path if we have a trained model
        if self._current_model_path is not None:
            self._patch_sequence_defender_model(cfg)

        return cfg

    def _patch_sequence_defender_model(self, cfg: ExperimentConfig) -> None:
        """
        Write the current model path into the sequence-model defender YAML so
        the orchestrator picks it up when building defenders.

        Rather than mutating the in-memory config (which may not flow through
        to the defender factory), we patch the on-disk YAML temporarily.
        This is a safe write because each round uses a fresh config copy.
        """
        import yaml

        for defender_name in cfg.defenders:
            try:
                defender_cfg = self._loader.load_defender(defender_name)
                if defender_cfg.detector_type.lower() != self._SEQ_DETECTOR_TYPE:
                    continue

                # Patch the YAML file
                yaml_path = (
                    self._loader.configs_dir
                    / "defenders"
                    / f"{defender_name}.yaml"
                )
                if not yaml_path.exists():
                    continue

                with yaml_path.open("r", encoding="utf-8") as fh:
                    data = yaml.safe_load(fh) or {}

                data["model_path"] = str(self._current_model_path)

                with yaml_path.open("w", encoding="utf-8") as fh:
                    yaml.safe_dump(data, fh, default_flow_style=False)

                logger.info(
                    "AdaptationLoop: patched '%s' model_path → %s.",
                    defender_name,
                    self._current_model_path,
                )
            except FileNotFoundError:
                pass
            except Exception as exc:
                logger.warning(
                    "AdaptationLoop: could not patch defender '%s': %s",
                    defender_name,
                    exc,
                )

    def _has_sequence_defender(self) -> bool:
        """Return True if any configured defender is a sequence_model type."""
        for name in self._base_config.defenders:
            try:
                cfg = self._loader.load_defender(name)
                if cfg.detector_type.lower() == self._SEQ_DETECTOR_TYPE:
                    return True
            except FileNotFoundError:
                pass
        return False

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _load_metrics(run_dir: Path) -> Optional[EvalMetrics]:
        """Load EvalMetrics from a run directory (None on failure)."""
        import json

        path = run_dir / "metrics.json"
        if not path.exists():
            return None
        try:
            with path.open() as fh:
                return EvalMetrics(**json.load(fh))
        except Exception as exc:
            logger.warning("Could not load metrics from %s: %s", path, exc)
            return None

    def _write_summaries(self, results: List[RoundResult]) -> None:
        """Write round_metrics.csv and round_summary.json to processed dir."""
        from cpsforge.adaptation.round_metrics import RoundSummary, write_round_metrics

        summaries = [
            RoundSummary.from_eval_metrics(
                round_idx=r.round_idx,
                run_id=r.run_id,
                metrics=r.metrics,
                hard_case_count=r.hard_case_count,
                hard_case_cumulative=r.hard_case_cumulative,
                retrained=r.retrained,
                model_path=str(r.model_path) if r.model_path else None,
                experiment_name=self._experiment_name,
            )
            for r in results
        ]

        write_round_metrics(
            summaries=summaries,
            output_dir=self._processed_dir,
            experiment_name=self._experiment_name,
        )

        # Also export hard-case bank manifest
        bank_manifest = self._processed_dir / "hard_case_bank.json"
        self._bank.export_manifest(bank_manifest)


# ---------------------------------------------------------------------------
# numpy import guard (used in _retrain synthetic fallback)
# ---------------------------------------------------------------------------
try:
    import numpy as np  # noqa: F401
except ImportError:
    pass
