"""
CPSForge Hard Case Extraction
================================
Classifies the detection outcome for every executed attack action in a run
and writes a ``hard_cases.json`` artifact.  Hard cases (missed or late
detections) are archived for later use by the closed-loop adaptation loop.

Outcome vocabulary
------------------
true_positive    : detected within the attack window + grace period
miss             : no detection at all (dry-run or attack succeeded on hardware)
late_detection   : first detection only after the grace window
no_impact        : attack executed but caused no measurable process impact (live runs)
rejected         : action blocked by shield -- not a detection failure

The grace period (``GRACE_STEPS``) allows for sensor lag and polling jitter:
at the default 500 ms poll rate, ``GRACE_STEPS=3`` gives a 1.5-second window.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from cpsforge.core.models import (
    AttackAction,
    DetectionEvent,
    HardCaseFailureMode,
    HardCaseRecord,
)

logger = logging.getLogger(__name__)

# Steps *after* the attack window ends that still count as timely detection.
# At 500 ms/step, GRACE_STEPS = 3  →  1.5-second grace period.
GRACE_STEPS: int = 3


def classify_attack_outcome(
    action: AttackAction,
    start_step: int,
    duration_steps: int,
    detections: List[DetectionEvent],
    attack_success: bool,
    dry_run: bool,
) -> Tuple[str, Optional[HardCaseFailureMode], float]:
    """
    Classify the detection outcome for a single executed attack action.

    Parameters
    ----------
    action:
        The executed :class:`AttackAction`.
    start_step:
        The polling step at which the attack was launched.
    duration_steps:
        How many polling steps the attack lasted.
    detections:
        All :class:`DetectionEvent` objects generated by defenders this run.
    attack_success:
        Whether ``scene.evaluate_attack_success`` returned True for this action.
    dry_run:
        If True, every undetected executed attack is flagged as a potential
        hard case (physical impact cannot be measured in dry-run mode).

    Returns
    -------
    (outcome_label, failure_mode, latency_steps)
        outcome_label  : one of the outcome vocabulary strings above
        failure_mode   : :class:`HardCaseFailureMode` or None if not a failure
        latency_steps  : steps from attack start to first detection (0 = not detected)
    """
    # Collect distinct detection step IDs at or after the attack start.
    det_steps = sorted(
        {ev.step_id for ev in detections if ev.step_id is not None and ev.step_id >= start_step}
    )

    attack_end_step = start_step + duration_steps
    window_end_step = attack_end_step + GRACE_STEPS

    first_det: Optional[int] = det_steps[0] if det_steps else None

    if first_det is None:
        # No detection at or after the attack start step.
        if attack_success or dry_run:
            return "miss", HardCaseFailureMode.MISS, 0.0
        else:
            return "no_impact", None, 0.0

    latency_steps = float(first_det - start_step)

    if first_det <= window_end_step:
        return "true_positive", None, latency_steps
    else:
        return "late_detection", HardCaseFailureMode.LATE_DETECTION, latency_steps


def extract_and_write_hard_cases(
    actions: List[AttackAction],
    detections: List[DetectionEvent],
    attack_start_steps: Dict[str, int],
    attack_success_map: Dict[str, bool],
    ground_truth_steps: Set[int],
    sampling_interval_ms: int,
    run_id: str,
    run_dir: Path,
    dry_run: bool = True,
) -> List[HardCaseRecord]:
    """
    Classify every executed attack action and persist ``hard_cases.json``.

    Parameters
    ----------
    actions:
        All :class:`AttackAction` objects generated this run.
    detections:
        All :class:`DetectionEvent` objects from defenders this run.
    attack_start_steps:
        Mapping of ``action_id`` → polling step when the attack was launched.
    attack_success_map:
        Mapping of ``action_id`` → bool from ``evaluate_attack_success``.
    ground_truth_steps:
        Set of step IDs where any attack was active (for reference only; not
        used in classification, which is per-action).
    sampling_interval_ms:
        Milliseconds per polling step (used to convert step latency to ms).
    run_id:
        Unique run identifier.
    run_dir:
        Directory to write ``hard_cases.json``.
    dry_run:
        Flag undetected executed attacks as hard cases in dry-run mode.

    Returns
    -------
    List of :class:`HardCaseRecord` objects (only those representing failures).
    """
    hard_cases: List[HardCaseRecord] = []
    outcomes: List[dict] = []

    for action in actions:
        if action.execution_status.value not in ("executed", "dry_run"):
            continue

        start_step = attack_start_steps.get(action.action_id)
        if start_step is None:
            continue

        duration_steps = max(1, int(action.duration_ms / sampling_interval_ms))
        attack_success = attack_success_map.get(action.action_id, False)

        outcome, failure_mode, lat_steps = classify_attack_outcome(
            action=action,
            start_step=start_step,
            duration_steps=duration_steps,
            detections=detections,
            attack_success=attack_success,
            dry_run=dry_run,
        )

        lat_ms = lat_steps * sampling_interval_ms
        outcomes.append({
            "action_id": action.action_id,
            "attack_type": action.attack_type.value,
            "target": action.target,
            "start_step": start_step,
            "duration_steps": duration_steps,
            "outcome": outcome,
            "detection_latency_ms": lat_ms,
            "failure_mode": failure_mode.value if failure_mode else None,
            "attack_success": attack_success,
        })

        if failure_mode is not None:
            rec = HardCaseRecord(
                run_id=run_id,
                attack_id=action.action_id,
                detector_outcome=outcome,
                failure_mode=failure_mode,
                trace_path=str(run_dir),
                summary=(
                    f"{action.attack_type.value} on '{action.target}' "
                    f"(step {start_step}, dur={duration_steps} steps): "
                    f"{outcome} | latency={lat_ms:.0f} ms"
                ),
                recommended_followup=(
                    "Add this trace window to the retraining set. "
                    "Consider tightening threshold / invariant rules for "
                    f"'{action.target}'."
                ),
            )
            hard_cases.append(rec)

    # Persist artifact.
    out_path = run_dir / "hard_cases.json"
    run_dir.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as fh:
        json.dump(
            {
                "run_id": run_id,
                "created_at": datetime.now(timezone.utc).isoformat(),
                "hard_case_count": len(hard_cases),
                "total_executed": len(outcomes),
                "outcomes": outcomes,
                "hard_cases": [r.model_dump(mode="json") for r in hard_cases],
            },
            fh,
            indent=2,
            default=str,
        )

    executed_count = sum(
        1 for a in actions if a.execution_status.value in ("executed", "dry_run")
    )
    logger.info(
        "Hard cases written to %s: %d hard case(s) from %d executed attacks.",
        out_path,
        len(hard_cases),
        executed_count,
    )
    return hard_cases


def load_hard_cases(run_dir: Path) -> List[HardCaseRecord]:
    """
    Load and parse ``hard_cases.json`` from a run directory.

    Returns an empty list if the file is absent or cannot be parsed.
    """
    path = run_dir / "hard_cases.json"
    if not path.exists():
        return []
    try:
        with path.open() as fh:
            data = json.load(fh)
        return [HardCaseRecord(**r) for r in data.get("hard_cases", [])]
    except Exception as exc:
        logger.warning("Could not load hard_cases.json from %s: %s", run_dir, exc)
        return []
